server:
  port: 8080
spring:
  #config env: dev/prod
  profiles:
    active: dev
  main:
    allow-circular-references: true
  application:
    name: AsianCuisine
  datasource:
    driver-class-name: ${ac.spring.datasource.driver-class-name}
    url: ${ac.spring.datasource.url}
    username: ${ac.spring.datasource.username}
    password: ${ac.spring.datasource.password}
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.asiancuisine.asiancuisine.entity
  config-location: classpath:/mybatis/mybatis-config.xml
logging:
  level:
    com.asiancuisine.asiancuisine: debug

ssh:
  host: ${ac.ssh.host}
  privateKeyPath: ${ac.ssh.privateKeyPath}
  passphrase: ${ac.ssh.passphrase}

aws:
  s3:
    accessKey: ${ac.aws.s3.accessKey}
    secretKey: ${ac.aws.s3.secretKey}
    region: ${ac.aws.s3.region}
    bucketName: ${ac.aws.s3.bucketName}

jwt:
  user-secret-key: asiancuisine
  # expire time
  user-ttl: 7200000
  # Set token name from frontend (in http header)
  user-token-name: token